In [10]:
import argparse
import torch
import datetime
import json
import yaml
import os
import numpy as np
import pandas as pd
from tqdm import tqdm

from src.main_model_table import TabCSDI
from src.utils_table import train, evaluate
from dataset_me_onehot import get_dataloader

In [33]:
path = "config/" + "data.yaml"
with open(path, "r") as f:
    config = yaml.safe_load(f)

config["model"]["is_unconditional"] = 0
config["model"]["test_missing_ratio"] = 0.8

print(json.dumps(config, indent=4))
train_loader, valid_loader, test_loader = get_dataloader(
    seed=1,
    nfold=5,
    batch_size=16,
    missing_ratio=0.8,
)

model = TabCSDI(config, "cuda").to("cuda")
model.load_state_dict(torch.load("./save/" + "data_fold5_20240403_141215" + "/model.pth"))
output = []
with tqdm(test_loader, mininterval=5.0, maxinterval=50.0) as it:
    for batch_no, test_batch in enumerate(it, start=1):
        print(model.evaluate(test_batch, 10)[0].permute(0, 1, 3, 2))
        #output.append(model.evaluate(test_batch, 10)[0].detach().cpu().numpy())


{
    "train": {
        "epochs": 2,
        "batch_size": 16,
        "lr": 0.0005
    },
    "diffusion": {
        "layers": 4,
        "channels": 128,
        "nheads": 4,
        "diffusion_embedding_dim": 128,
        "beta_start": 0.0001,
        "beta_end": 0.5,
        "num_steps": 100,
        "schedule": "quad",
        "mixed": false
    },
    "model": {
        "is_unconditional": 0,
        "timeemb": 128,
        "featureemb": 8,
        "target_strategy": "random",
        "mixed": false,
        "test_missing_ratio": 0.8
    }
}
--------Normalized dataset loaded--------
Dataset size:2000 entries
--------Normalized dataset loaded--------
--------Normalized dataset loaded--------
--------Normalized dataset loaded--------
Training dataset size: 1600
Validation dataset size: 0
Testing dataset size: 400


  4%|███▎                                                                               | 1/25 [00:05<02:22,  5.94s/it]

tensor([[[[ 8.0488e+03],
          [ 1.2067e+04],
          [ 7.4153e-01],
          [-9.2320e+03]],

         [[ 6.5164e+04],
          [-1.5685e+03],
          [ 8.4201e+01],
          [-5.6506e+04]],

         [[ 4.5722e+02],
          [-3.3279e+04],
          [-5.1131e+01],
          [ 7.3295e+04]],

         [[ 6.1969e+03],
          [ 6.1357e+03],
          [ 1.1432e+03],
          [ 1.5424e+04]],

         [[-1.8990e+04],
          [ 5.3055e+04],
          [ 6.6059e-02],
          [ 5.6946e+04]],

         [[-3.7841e+04],
          [ 3.6712e+04],
          [ 1.4164e-01],
          [ 1.4698e+04]],

         [[-2.3145e+04],
          [ 7.8565e+03],
          [-2.4004e+04],
          [ 4.1987e+04]],

         [[ 2.2249e+04],
          [ 9.5121e+04],
          [-4.5207e-01],
          [-1.3577e+04]],

         [[ 2.3273e+04],
          [-2.3210e+04],
          [ 1.6354e-01],
          [ 2.7291e+04]],

         [[ 3.2459e+03],
          [-1.7008e+02],
          [ 1.8032e+03],
       

  8%|██████▋                                                                            | 2/25 [00:11<02:17,  5.98s/it]

tensor([[[[ 1.3425e+04],
          [-1.5674e+04],
          [ 6.4134e-01],
          [ 6.6830e+04]],

         [[-1.1977e+03],
          [-1.3612e+04],
          [-7.6416e+03],
          [ 2.3694e+03]],

         [[-1.2904e+04],
          [ 2.2079e+04],
          [-8.7124e+03],
          [-1.4807e+04]],

         [[ 5.7401e+04],
          [-3.4628e+04],
          [ 9.8460e-02],
          [ 1.5971e+04]],

         [[ 5.2298e+04],
          [ 4.0385e+03],
          [-2.1276e+02],
          [-4.4313e+03]],

         [[-3.6497e+04],
          [-3.7308e+04],
          [-1.7790e+01],
          [ 7.9670e+03]],

         [[-2.4456e+04],
          [-6.4523e+04],
          [-7.7473e+03],
          [-3.3727e+03]],

         [[ 4.4027e+04],
          [ 4.4401e+03],
          [ 3.9379e+03],
          [-1.6296e+04]],

         [[ 2.0725e+04],
          [-1.4049e+03],
          [-8.3501e+03],
          [ 7.7406e+04]],

         [[ 3.8934e+04],
          [-3.1373e+04],
          [ 7.6642e+02],
       

 12%|█████████▉                                                                         | 3/25 [00:17<02:10,  5.91s/it]

tensor([[[[ 2.5310e+04],
          [-2.7199e+04],
          [ 1.1751e+04],
          [-1.6262e+04]],

         [[-1.0144e+05],
          [-2.4670e+04],
          [ 4.1402e+03],
          [ 2.2955e+03]],

         [[-2.2986e+03],
          [ 2.7981e+04],
          [ 2.2862e+02],
          [ 6.3456e+04]],

         [[ 5.2908e+04],
          [-3.0293e+04],
          [ 3.1851e+01],
          [ 3.8501e+04]],

         [[ 1.0060e+04],
          [ 3.8098e+04],
          [ 1.3781e+02],
          [-1.8516e+04]],

         [[ 1.1764e+04],
          [ 9.1625e+03],
          [-5.7043e+02],
          [ 2.9511e+04]],

         [[ 5.0750e+04],
          [ 2.0256e+04],
          [ 2.9168e+03],
          [-5.5813e+04]],

         [[-6.8553e+04],
          [-1.9550e+04],
          [-1.9838e+02],
          [ 5.6163e+04]],

         [[-1.9719e+04],
          [ 5.6319e+03],
          [ 9.7943e+02],
          [ 2.1564e+04]],

         [[-7.6950e+03],
          [ 7.9681e+04],
          [ 1.0575e+03],
       

 16%|█████████████▎                                                                     | 4/25 [00:23<02:04,  5.93s/it]

tensor([[[[ 3.0921e+04],
          [-3.8200e+04],
          [ 2.3686e-01],
          [-1.9256e+04]],

         [[ 3.9723e+04],
          [ 4.8973e+03],
          [ 8.8490e+02],
          [-3.2538e+04]],

         [[-5.9610e+04],
          [-3.9390e+04],
          [ 3.0925e+01],
          [-1.7073e+04]],

         [[ 5.1132e+04],
          [-2.5993e+04],
          [-1.5913e+02],
          [-4.7021e+04]],

         [[-9.5180e+03],
          [ 3.6581e+04],
          [ 1.2192e+03],
          [-1.1930e+04]],

         [[-3.6235e+04],
          [ 3.4271e+04],
          [ 4.3826e+01],
          [-1.5287e+04]],

         [[-1.1090e+04],
          [-1.4970e+04],
          [ 4.6139e-01],
          [ 1.1507e+05]],

         [[ 6.4300e+04],
          [ 6.7003e+03],
          [ 1.0133e+04],
          [-3.7788e+04]],

         [[-4.6277e+04],
          [ 5.7565e+04],
          [ 1.0252e+01],
          [ 3.0562e+04]],

         [[ 8.0661e+04],
          [-1.0330e+04],
          [-2.8237e+04],
       

 20%|████████████████▌                                                                  | 5/25 [00:29<02:00,  6.01s/it]

tensor([[[[-2.5603e+04],
          [ 3.9296e+04],
          [ 4.7306e+00],
          [ 5.2721e+03]],

         [[ 3.6328e+04],
          [-3.3145e+03],
          [ 3.4164e+02],
          [ 5.1197e+04]],

         [[ 5.5194e+04],
          [-3.1114e+03],
          [-1.0917e-01],
          [-1.8691e+03]],

         [[ 7.6497e+03],
          [ 2.2493e+04],
          [ 2.1905e+00],
          [ 1.7322e+04]],

         [[-7.3163e+03],
          [-7.4676e+04],
          [ 5.4509e+03],
          [ 7.6010e+03]],

         [[ 4.9178e+04],
          [-6.6718e+04],
          [ 2.4917e+03],
          [ 3.6000e+04]],

         [[-6.4772e+02],
          [-5.2272e+04],
          [ 2.4556e+03],
          [ 5.6643e+03]],

         [[ 3.8474e+04],
          [ 8.5126e+04],
          [ 2.8106e-01],
          [-2.0066e+04]],

         [[ 5.3761e+02],
          [ 9.5969e+03],
          [ 5.0236e+04],
          [-1.9442e+04]],

         [[-2.1471e+03],
          [ 7.7218e+04],
          [ 9.1191e+02],
       

 24%|███████████████████▉                                                               | 6/25 [00:36<01:54,  6.05s/it]

tensor([[[[ 1.1202e+04],
          [-4.3556e+04],
          [-1.3230e+01],
          [-4.4055e+04]],

         [[-2.2201e+03],
          [ 5.4803e+04],
          [ 3.8175e+00],
          [-1.4055e+03]],

         [[-1.2403e+04],
          [ 6.2609e+04],
          [ 3.3865e+03],
          [ 5.2407e+04]],

         [[ 4.9189e+04],
          [ 5.4197e+04],
          [ 3.9528e+03],
          [-5.7264e+03]],

         [[ 1.7340e+04],
          [ 2.2837e+04],
          [ 7.9288e+03],
          [ 3.7828e+04]],

         [[-3.5357e+04],
          [ 3.1870e+03],
          [-2.4061e-01],
          [ 1.5063e+04]],

         [[-1.9806e+04],
          [-3.7360e+04],
          [-6.5018e-01],
          [ 4.7367e+04]],

         [[-3.2295e+04],
          [-1.4635e+04],
          [-5.1995e+00],
          [ 2.3318e+04]],

         [[ 6.8675e+04],
          [-1.3123e+04],
          [ 3.1350e-01],
          [ 2.4585e+04]],

         [[ 2.9728e+04],
          [ 1.0232e+03],
          [ 4.8686e+01],
       

 28%|███████████████████████▏                                                           | 7/25 [00:42<01:49,  6.10s/it]

tensor([[[[ 1.2966e+04],
          [ 1.4792e+04],
          [ 4.1168e+04],
          [-3.7668e+03]],

         [[-7.5908e+04],
          [ 7.8864e+04],
          [ 5.5410e+03],
          [-1.3183e+04]],

         [[ 2.3973e+04],
          [ 1.9843e+04],
          [-1.8552e+04],
          [-5.4421e+03]],

         [[ 5.7506e+04],
          [-3.7665e+04],
          [ 1.2110e+04],
          [-5.4608e+03]],

         [[ 8.8752e+03],
          [-2.5488e+04],
          [-6.5148e+04],
          [-1.6445e+04]],

         [[ 1.0034e+05],
          [-2.6502e+04],
          [ 4.1313e+03],
          [-5.0126e+03]],

         [[-3.9850e+04],
          [-1.9743e+04],
          [ 9.2955e+04],
          [-2.8878e+04]],

         [[ 1.0747e+04],
          [-3.7889e+04],
          [-3.0687e+04],
          [ 9.3457e+03]],

         [[ 3.1284e+04],
          [ 1.5410e+03],
          [-1.2345e+04],
          [ 5.6074e+04]],

         [[-2.7592e+04],
          [-4.4391e+04],
          [ 9.8569e+04],
       

 32%|██████████████████████████▌                                                        | 8/25 [00:47<01:41,  6.00s/it]

tensor([[[[-1.9810e+04],
          [-1.0854e+04],
          [ 1.1516e+04],
          [-5.3461e+04]],

         [[ 5.3435e+04],
          [ 6.7021e+04],
          [ 1.1285e+05],
          [-2.3619e+04]],

         [[ 5.8816e+04],
          [ 4.7940e+04],
          [-2.7942e+03],
          [ 4.5003e+04]],

         [[-4.9482e+04],
          [-9.5466e+03],
          [ 3.2307e+03],
          [-6.7721e+04]],

         [[ 2.5368e+04],
          [ 3.2680e+04],
          [-6.5348e+04],
          [ 6.5478e+04]],

         [[-4.7170e+04],
          [ 3.1505e+04],
          [-5.8953e+04],
          [-1.1923e+04]],

         [[-4.2181e+04],
          [ 3.9502e+04],
          [ 5.0659e+04],
          [-3.0320e+03]],

         [[ 3.2004e+04],
          [ 5.7519e+04],
          [-5.1244e+03],
          [-1.3107e+04]],

         [[-2.9618e+04],
          [ 2.2421e+04],
          [ 1.2657e+04],
          [-2.1993e+04]],

         [[ 2.4369e+04],
          [-9.0747e+03],
          [-7.8866e+03],
       

 36%|█████████████████████████████▉                                                     | 9/25 [00:53<01:35,  5.95s/it]

tensor([[[[-5.9037e+04],
          [-1.4064e+04],
          [ 1.9803e+04],
          [-3.0967e+04]],

         [[-1.5546e+04],
          [-3.1177e+04],
          [ 4.0626e-01],
          [ 1.9295e+03]],

         [[-1.7711e+04],
          [ 1.2063e+04],
          [ 3.0706e-01],
          [ 7.7606e+04]],

         [[-2.0643e+04],
          [-1.9917e+04],
          [ 4.1221e+03],
          [ 4.5707e+04]],

         [[ 2.9519e+04],
          [ 1.8385e+04],
          [ 5.2322e-01],
          [-2.7010e+04]],

         [[ 6.2103e+04],
          [ 3.2126e+04],
          [ 2.4630e-01],
          [ 8.5641e+03]],

         [[ 2.7144e+04],
          [-7.0130e+03],
          [ 7.1506e+02],
          [ 4.4040e+04]],

         [[ 4.6511e+03],
          [-4.9626e+03],
          [ 3.9160e+03],
          [ 2.9252e+04]],

         [[-1.6038e+04],
          [ 4.0483e+04],
          [-3.5444e-03],
          [ 6.9754e+03]],

         [[ 3.3886e+04],
          [ 9.8246e+04],
          [ 4.3435e+04],
       

 40%|████████████████████████████████▊                                                 | 10/25 [00:59<01:29,  5.94s/it]

tensor([[[[ 8.2936e+04],
          [ 1.3568e+04],
          [-9.5032e+03],
          [-4.4643e+03]],

         [[-2.6137e+04],
          [ 6.8097e+04],
          [ 1.4066e+04],
          [ 6.6591e+04]],

         [[ 5.9076e+04],
          [ 3.7703e+04],
          [ 2.5767e+04],
          [ 5.3355e+04]],

         [[ 5.7684e+03],
          [ 2.0723e+04],
          [ 7.9589e+03],
          [ 4.0376e+04]],

         [[ 2.4175e+04],
          [ 8.2031e+02],
          [-6.2900e+03],
          [ 4.0080e+04]],

         [[-6.1424e+03],
          [-1.7267e+04],
          [-1.5314e+03],
          [ 4.1363e+04]],

         [[ 3.4859e+04],
          [-9.0835e+03],
          [ 6.9471e+03],
          [-9.9821e+04]],

         [[-3.2332e+04],
          [ 4.2467e+04],
          [ 1.9959e+04],
          [ 6.3702e+04]],

         [[-7.2623e+04],
          [-4.6342e+04],
          [ 2.8659e+03],
          [ 4.9898e+04]],

         [[ 2.7562e+04],
          [-4.5686e+04],
          [ 1.2353e+04],
       

 44%|████████████████████████████████████                                              | 11/25 [01:05<01:22,  5.91s/it]

tensor([[[[ 5.3447e+04],
          [ 3.1889e+04],
          [-3.0949e-01],
          [ 5.8199e+04]],

         [[-5.7111e+04],
          [ 6.8661e+04],
          [ 1.0719e+04],
          [ 3.0999e+04]],

         [[ 5.9630e+04],
          [-4.9873e+04],
          [-9.5857e-01],
          [ 3.6632e+04]],

         [[ 3.5822e+03],
          [ 4.3753e+04],
          [ 1.8125e+03],
          [-2.6617e+03]],

         [[ 5.2065e+04],
          [ 1.1392e+05],
          [ 4.1958e-01],
          [ 4.3070e+04]],

         [[-7.8317e+04],
          [ 4.9267e+04],
          [ 6.3807e-01],
          [ 1.8766e+04]],

         [[ 7.3088e+04],
          [-8.8712e+03],
          [ 2.6039e+01],
          [ 3.6119e+04]],

         [[-4.4000e+04],
          [-4.5547e+03],
          [ 8.4235e+01],
          [ 4.0663e+04]],

         [[-1.3067e+04],
          [-3.4863e+03],
          [-5.4343e-02],
          [-3.9423e+04]],

         [[-3.1086e+04],
          [ 4.7641e+04],
          [ 9.2942e+00],
       

 48%|███████████████████████████████████████▎                                          | 12/25 [01:11<01:16,  5.92s/it]

tensor([[[[-2.2159e+04],
          [ 2.1512e+04],
          [-1.0300e+04],
          [-2.4620e+03]],

         [[-4.4071e+04],
          [ 1.9661e+04],
          [-2.1394e+04],
          [-1.9517e+04]],

         [[ 2.5270e+04],
          [ 2.4206e+04],
          [ 8.3575e-01],
          [-3.9507e+04]],

         [[-4.6824e+03],
          [-3.7089e+04],
          [ 1.9381e+00],
          [-1.3744e+04]],

         [[ 3.2406e+03],
          [ 2.4188e+03],
          [-9.8116e+03],
          [ 4.6414e+04]],

         [[ 3.3500e+04],
          [ 4.1696e+04],
          [ 1.3651e+01],
          [ 4.9061e+04]],

         [[-1.7759e+04],
          [ 1.1389e+04],
          [ 1.0767e+04],
          [ 4.0432e+04]],

         [[-3.2914e+04],
          [ 2.2875e+04],
          [-2.1155e+04],
          [ 1.5676e+04]],

         [[-2.4807e+04],
          [ 2.3222e+04],
          [ 1.2133e+01],
          [ 3.6674e+04]],

         [[-7.3355e+03],
          [ 3.8326e+04],
          [ 4.8811e+00],
       

 52%|██████████████████████████████████████████▋                                       | 13/25 [01:17<01:11,  5.93s/it]

tensor([[[[ 1.6036e+03],
          [ 2.8027e+04],
          [ 7.8806e+04],
          [ 8.8148e+04]],

         [[ 2.3415e+04],
          [ 2.5092e+04],
          [ 8.7970e+04],
          [ 1.1109e+04]],

         [[-9.7950e+03],
          [ 2.2068e+03],
          [ 3.5260e+04],
          [ 3.9161e+04]],

         [[ 6.1906e+04],
          [ 3.8916e+04],
          [ 2.5550e+04],
          [ 2.6591e+04]],

         [[-1.1734e+04],
          [ 3.0580e+03],
          [ 7.5556e+04],
          [ 1.0834e+05]],

         [[ 1.5752e+04],
          [-5.3715e+04],
          [ 1.1675e+03],
          [ 1.4950e+04]],

         [[ 3.0109e+04],
          [ 4.6156e+04],
          [-1.3999e+04],
          [ 1.5449e+04]],

         [[-1.5567e+03],
          [-5.2282e+04],
          [-3.2026e+04],
          [-4.4111e+04]],

         [[ 2.7010e+03],
          [ 3.5050e+04],
          [ 5.0464e+04],
          [-3.6232e+03]],

         [[ 1.9633e+04],
          [ 1.7770e+04],
          [ 6.2057e+03],
       

 56%|█████████████████████████████████████████████▉                                    | 14/25 [01:23<01:05,  5.91s/it]

tensor([[[[ 3.9624e+03],
          [ 3.2865e+04],
          [-4.3383e+01],
          [ 3.3315e+04]],

         [[ 1.3962e+04],
          [-7.4035e+03],
          [ 7.3179e+02],
          [ 8.3111e+04]],

         [[-3.7220e+04],
          [ 6.8221e+04],
          [ 9.7896e+00],
          [ 1.6973e+04]],

         [[ 2.0807e+04],
          [ 3.2798e+04],
          [ 1.8142e-01],
          [ 1.0851e+05]],

         [[-2.2036e+04],
          [-7.6820e+04],
          [ 6.2485e+02],
          [-9.8931e+03]],

         [[-3.0498e+04],
          [-3.3507e+04],
          [ 2.6183e-01],
          [ 6.0206e+04]],

         [[-1.8390e+04],
          [ 2.6429e+04],
          [ 1.2638e+02],
          [-1.6242e+04]],

         [[ 8.0156e+04],
          [ 1.3278e+04],
          [ 6.6566e-01],
          [-1.0693e+04]],

         [[-2.3279e+04],
          [-9.7993e+03],
          [ 3.1681e+00],
          [ 9.6444e+02]],

         [[ 4.0303e+04],
          [-2.9140e+03],
          [ 7.6170e-01],
       

 60%|█████████████████████████████████████████████████▏                                | 15/25 [01:29<00:59,  5.92s/it]

tensor([[[[-4.2092e+03],
          [-3.0141e+04],
          [ 2.8542e+01],
          [ 1.1513e+04]],

         [[-1.4746e+03],
          [-4.0717e+04],
          [-7.5182e+03],
          [-4.9603e+03]],

         [[-4.5263e+04],
          [ 3.4074e+04],
          [ 4.4915e-01],
          [-3.2338e+04]],

         [[-8.1945e+04],
          [-4.9276e+04],
          [ 3.1757e-01],
          [-4.6538e+03]],

         [[-1.2632e+04],
          [-2.1362e+04],
          [ 3.0875e+01],
          [ 1.1765e+04]],

         [[ 3.0570e+04],
          [-4.5671e+04],
          [ 1.9104e-01],
          [ 5.1007e+04]],

         [[-1.2310e+04],
          [ 5.9107e+04],
          [ 2.2868e+01],
          [ 4.5633e+03]],

         [[ 9.5735e+03],
          [ 3.4405e+04],
          [ 1.9832e+01],
          [ 4.6215e+04]],

         [[ 2.3639e+04],
          [-1.0612e+04],
          [ 1.6882e+01],
          [-4.2445e+03]],

         [[-1.7392e+04],
          [ 3.1404e+04],
          [-1.4988e-01],
       

 64%|████████████████████████████████████████████████████▍                             | 16/25 [01:35<00:53,  5.92s/it]

tensor([[[[ 3.7004e+04],
          [ 2.4188e+04],
          [-4.2008e+04],
          [ 3.3001e+04]],

         [[ 2.4468e+04],
          [ 2.1028e+04],
          [ 1.9649e+04],
          [ 8.7962e+03]],

         [[-1.4850e+04],
          [ 5.3054e+03],
          [ 1.5707e+04],
          [-7.0047e+03]],

         [[-1.3217e+04],
          [ 1.7820e+04],
          [-4.2967e+04],
          [ 1.3515e+03]],

         [[-3.3674e+04],
          [-2.4824e+04],
          [ 1.7274e+04],
          [ 2.1016e+04]],

         [[ 2.7358e+04],
          [-5.5377e+04],
          [-7.4132e+03],
          [-1.6661e+04]],

         [[ 2.1733e+04],
          [ 1.4910e+04],
          [-3.4812e+04],
          [ 3.7021e+04]],

         [[-4.9234e+04],
          [ 2.0247e+04],
          [ 1.5987e+04],
          [ 6.6436e+03]],

         [[-3.0187e+04],
          [ 7.2466e+04],
          [ 1.2995e+04],
          [ 4.0942e+04]],

         [[ 7.8784e+04],
          [ 3.6185e+04],
          [ 1.6937e+04],
       

 68%|███████████████████████████████████████████████████████▊                          | 17/25 [01:41<00:47,  5.88s/it]

tensor([[[[-2.0548e+04],
          [-1.0166e+04],
          [-7.4798e+02],
          [ 5.6524e+03]],

         [[-3.0851e+04],
          [-3.2176e+04],
          [ 4.0566e-01],
          [-3.9496e+04]],

         [[ 4.3985e+03],
          [-1.9139e+04],
          [ 5.3397e+03],
          [ 6.8862e+04]],

         [[-9.4877e+03],
          [ 3.5006e+04],
          [ 7.3825e+03],
          [ 1.9000e+04]],

         [[ 8.2045e+03],
          [ 6.6714e+02],
          [-5.9115e+01],
          [ 1.1098e+04]],

         [[-5.5700e+03],
          [ 3.9833e+04],
          [-1.6938e+02],
          [-5.9098e+03]],

         [[ 3.6265e+03],
          [ 1.1755e+04],
          [-2.8894e+04],
          [ 1.5934e+04]],

         [[-2.7165e+04],
          [ 2.2886e+04],
          [ 2.5658e-01],
          [-3.8729e+03]],

         [[ 6.5889e+04],
          [ 2.0706e+02],
          [ 6.6468e-01],
          [-2.5009e+04]],

         [[ 4.3081e+04],
          [ 4.2736e+04],
          [ 3.5050e+02],
       

 72%|███████████████████████████████████████████████████████████                       | 18/25 [01:46<00:41,  5.89s/it]

tensor([[[[ 2.3363e+04],
          [ 1.3338e+04],
          [ 6.1261e+02],
          [-2.2999e+04]],

         [[ 2.4263e+04],
          [-2.1318e+04],
          [-2.2902e+04],
          [-5.0130e+04]],

         [[-4.6709e+03],
          [ 2.1532e+04],
          [ 2.7181e+00],
          [-7.5012e+03]],

         [[ 1.3981e+04],
          [ 2.8009e+04],
          [ 2.3302e-01],
          [-1.1889e+04]],

         [[ 4.0357e+04],
          [-2.3634e+04],
          [ 7.5559e+01],
          [ 2.6836e+04]],

         [[ 7.9787e+03],
          [-1.7360e+04],
          [ 3.0206e+02],
          [ 2.4584e+04]],

         [[ 2.0828e+04],
          [-2.9629e+04],
          [ 5.4890e-01],
          [ 3.2201e+04]],

         [[ 3.2738e+04],
          [ 2.1247e+04],
          [ 2.2704e+01],
          [ 2.8671e+04]],

         [[ 4.5361e+04],
          [-7.6081e+04],
          [ 7.7684e+02],
          [ 1.1538e+04]],

         [[ 3.9779e+04],
          [-1.5872e+04],
          [-1.2330e+02],
       

 76%|██████████████████████████████████████████████████████████████▎                   | 19/25 [01:52<00:35,  5.89s/it]

tensor([[[[ 6.8919e+03],
          [-3.0887e+04],
          [ 3.2840e-01],
          [ 2.1148e+04]],

         [[-7.8582e+03],
          [ 9.7002e+03],
          [ 6.2697e+01],
          [-1.1719e+04]],

         [[ 3.7027e+04],
          [ 1.8038e+04],
          [ 9.5183e-02],
          [ 3.4063e+04]],

         [[-4.4138e+04],
          [ 3.2938e+04],
          [ 8.4073e-02],
          [ 7.9678e+02]],

         [[-2.5884e+04],
          [-9.3180e+04],
          [ 1.8634e+02],
          [-3.2775e+03]],

         [[ 3.7187e+04],
          [-1.3806e+03],
          [ 1.7698e+01],
          [ 3.3671e+03]],

         [[-9.1649e+02],
          [ 5.3686e+03],
          [ 3.9347e+03],
          [ 2.4889e+04]],

         [[ 7.7021e+04],
          [ 3.1218e+03],
          [ 9.2402e+02],
          [ 1.4488e+04]],

         [[-4.3237e+04],
          [ 1.6387e+04],
          [ 1.9396e+03],
          [ 4.0113e+04]],

         [[-1.3698e+04],
          [ 7.1961e+04],
          [-2.3731e+03],
       

 80%|█████████████████████████████████████████████████████████████████▌                | 20/25 [01:58<00:29,  5.90s/it]

tensor([[[[ 1.7068e+03],
          [ 1.8903e+04],
          [ 2.9311e+03],
          [ 3.6961e+04]],

         [[ 3.0546e+04],
          [-7.6551e+03],
          [ 3.6375e+02],
          [ 7.0735e+03]],

         [[ 2.3826e+04],
          [ 2.4875e+04],
          [-3.4029e+00],
          [-1.1086e+04]],

         [[-2.6086e+04],
          [ 5.3549e+04],
          [-8.6450e+00],
          [-7.4264e+03]],

         [[ 2.3107e+03],
          [ 6.7251e+04],
          [-7.9247e-01],
          [-1.7225e+04]],

         [[-2.2217e+04],
          [-1.9652e+04],
          [ 3.1613e+03],
          [-9.0037e+04]],

         [[ 3.3452e+04],
          [ 1.8058e+04],
          [ 4.6737e-01],
          [ 2.0630e+04]],

         [[ 7.5636e+03],
          [-4.0044e+04],
          [-3.2007e+03],
          [ 5.1486e+04]],

         [[-3.6342e+03],
          [-6.5435e+03],
          [ 1.9059e-02],
          [-8.6295e+02]],

         [[ 3.2862e+04],
          [ 7.9144e+04],
          [ 6.4126e+01],
       

 84%|████████████████████████████████████████████████████████████████████▉             | 21/25 [02:04<00:24,  6.00s/it]

tensor([[[[ 5.1601e+04],
          [-2.6011e+04],
          [ 1.5055e+02],
          [ 2.3467e+04]],

         [[-2.8845e+04],
          [ 2.0005e+04],
          [ 3.2627e+03],
          [ 1.6295e+04]],

         [[ 3.3226e+04],
          [ 2.3619e+04],
          [-1.2759e+01],
          [-2.2945e+04]],

         [[ 5.5723e+03],
          [ 2.6509e+04],
          [ 2.6159e-01],
          [ 3.5438e+04]],

         [[ 1.0415e+05],
          [ 2.8886e+04],
          [ 6.0197e-01],
          [ 2.8512e+04]],

         [[-1.4233e+04],
          [ 6.7341e+04],
          [ 1.0306e+00],
          [-2.3881e+04]],

         [[-4.2378e+03],
          [-5.0946e+04],
          [-9.5359e-02],
          [ 1.0449e+04]],

         [[ 1.8234e+04],
          [-1.0783e+04],
          [-5.5390e+01],
          [ 3.6587e+04]],

         [[ 3.5147e+04],
          [ 6.6972e+04],
          [ 2.5790e+03],
          [ 7.7751e+04]],

         [[-2.5660e+04],
          [ 3.9600e+04],
          [ 4.9671e-01],
       

 88%|████████████████████████████████████████████████████████████████████████▏         | 22/25 [02:11<00:18,  6.01s/it]

tensor([[[[ 3.1340e+04],
          [ 3.0525e+04],
          [ 4.6976e+03],
          [ 5.2164e+04]],

         [[ 1.6784e+04],
          [-1.4308e+04],
          [ 1.7834e+04],
          [ 5.5266e+04]],

         [[ 1.9979e+04],
          [ 7.6997e+03],
          [ 4.7393e+04],
          [ 2.5341e+04]],

         [[ 4.6146e+04],
          [-4.9660e+04],
          [ 2.2951e+04],
          [ 1.7048e+03]],

         [[ 7.0089e+04],
          [ 1.8534e+04],
          [ 2.1388e+04],
          [ 3.8969e+04]],

         [[-1.5687e+04],
          [-6.7760e+04],
          [ 3.5860e+04],
          [ 3.4269e+04]],

         [[-1.2594e+04],
          [-3.9255e+04],
          [ 4.0173e+03],
          [-1.9432e+04]],

         [[ 3.4576e+04],
          [ 2.7651e+04],
          [-4.4057e+03],
          [-4.7104e+04]],

         [[-4.9963e+04],
          [-4.3002e+04],
          [-1.0055e+04],
          [ 2.4909e+04]],

         [[ 3.5278e+04],
          [ 2.1308e+04],
          [-5.2473e+04],
       

 92%|███████████████████████████████████████████████████████████████████████████▍      | 23/25 [02:17<00:12,  6.14s/it]

tensor([[[[ 1.1175e+04],
          [ 6.8283e+04],
          [ 3.6266e+01],
          [-9.4416e+03]],

         [[-3.4023e+04],
          [ 8.4031e+03],
          [ 1.3480e-01],
          [ 2.6199e+04]],

         [[-4.8484e+04],
          [ 7.3265e+03],
          [ 5.1505e-01],
          [-1.5889e+04]],

         [[-6.2696e+04],
          [ 4.2867e+04],
          [ 7.6422e+03],
          [ 3.5216e+04]],

         [[ 1.2459e+04],
          [ 4.6356e+04],
          [-1.9137e+02],
          [ 6.4011e+03]],

         [[-3.7113e+04],
          [ 3.1970e+04],
          [-1.6789e+02],
          [ 1.3219e+04]],

         [[-1.3201e+04],
          [-1.4542e+04],
          [ 1.0792e+03],
          [-3.2873e+04]],

         [[ 1.0240e+05],
          [-2.3890e+03],
          [ 7.3128e-01],
          [ 3.0943e+04]],

         [[ 2.7827e+04],
          [ 1.5204e+04],
          [ 7.2174e-01],
          [ 2.0070e+04]],

         [[ 2.6855e+04],
          [ 5.7492e+04],
          [ 5.7628e-01],
       

 96%|██████████████████████████████████████████████████████████████████████████████▋   | 24/25 [02:23<00:06,  6.21s/it]

tensor([[[[ 6.7956e+04],
          [ 8.1842e+03],
          [ 6.3958e-02],
          [ 1.7733e+04]],

         [[-5.2059e+04],
          [-2.9739e+04],
          [ 1.4343e+04],
          [ 3.7914e+03]],

         [[-4.9934e+04],
          [-7.6910e+03],
          [ 1.2332e+00],
          [ 5.9113e+04]],

         [[-1.5143e+04],
          [ 1.6631e+04],
          [-2.0545e-01],
          [ 4.4740e+04]],

         [[-6.0200e+04],
          [ 1.8854e+04],
          [-2.2898e+04],
          [ 2.0537e+04]],

         [[-2.8768e+04],
          [ 4.4158e+04],
          [-1.2593e+01],
          [-2.0360e+03]],

         [[-2.3960e+04],
          [ 3.7093e+03],
          [ 5.6258e+02],
          [-5.6372e+04]],

         [[ 1.9373e+04],
          [-5.3064e+03],
          [ 2.2529e+03],
          [-3.1209e+04]],

         [[-5.2342e+04],
          [-1.1513e+04],
          [-8.0949e-02],
          [-5.5229e+03]],

         [[ 1.5608e+04],
          [ 3.5647e+04],
          [-3.3532e+01],
       

100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [02:30<00:00,  6.03s/it]

tensor([[[[ 6.8790e+04],
          [ 1.5591e+04],
          [ 4.1703e+03],
          [ 1.6227e+04]],

         [[ 6.8490e+04],
          [-5.6574e+04],
          [ 4.1583e-01],
          [ 2.7524e+04]],

         [[-9.8050e+03],
          [ 4.2131e+04],
          [ 1.2215e+02],
          [-1.4858e+03]],

         [[-1.4911e+04],
          [-1.0711e+04],
          [-2.0421e+02],
          [ 2.3061e+04]],

         [[-2.9314e+04],
          [ 6.2877e+04],
          [ 3.4224e+02],
          [-4.0790e+04]],

         [[ 2.7072e+04],
          [-1.3119e+04],
          [ 3.7937e-01],
          [ 6.1088e+04]],

         [[ 1.5967e+04],
          [-7.9492e+03],
          [-4.8634e+00],
          [ 4.0877e+03]],

         [[ 1.2921e+04],
          [-2.2099e+04],
          [-8.0344e+02],
          [ 3.5699e+04]],

         [[ 3.0397e+04],
          [-2.7668e+04],
          [-4.3153e+02],
          [ 1.1004e+05]],

         [[ 4.2893e+03],
          [ 2.3361e+04],
          [ 1.0152e+01],
       

In [29]:
n1 = np.concatenate(n1, axis=0)

#output = np.concatenate(output, axis=0)

In [31]:
output

[array([[[[-7.18326025e+03,  2.05001484e+04,  3.50153555e+04,
           -1.37723818e+04]],
 
         [[ 2.79598750e+04, -2.01517163e+03,  4.03349121e+02,
            6.89249219e+04]],
 
         [[ 1.24309121e+04,  5.45741250e+04,  1.13513207e+00,
            9.01679062e+04]],
 
         [[ 3.30832539e+04, -5.17266016e+03,  5.61342344e+04,
            7.59462549e+03]],
 
         [[ 6.48440088e+03,  8.63741797e+03,  5.92779785e+02,
            3.69845312e+04]],
 
         [[-1.80808594e+04,  4.46774170e+03,  8.36505188e+02,
            4.12941016e+04]],
 
         [[ 5.50005117e+04, -9.43202441e+03, -5.37658691e+03,
           -1.55760625e+04]],
 
         [[-7.65691562e+04, -1.10190771e+04,  1.63553562e+01,
            4.07016094e+04]],
 
         [[-3.18337246e+04,  3.94420156e+04,  2.94109980e+04,
           -1.22465498e+04]],
 
         [[ 9.62282471e+02,  2.09642988e+04, -4.18262988e+03,
            9.11065332e+03]]],
 
 
        [[[-1.25193799e+04, -7.19534062e+04,  2.36620545e

In [1]:
import datetime
import yaml
import torch
from src.main_model_table import TabCSDI
from src.utils_table import train, evaluate_onehot

from dataset_me_onehot import get_dataloader
exe_name = "data"
path = "config/" + "data.yaml"
with open(path, "r") as f:
    config = yaml.safe_load(f)
    
config["model"]["is_unconditional"] = 0
config["model"]["test_missing_ratio"] = 0.8

train_loader, valid_loader, test_loader = get_dataloader(
    seed=1,
    nfold=5,
    batch_size=config["train"]["batch_size"],
    missing_ratio=config["model"]["test_missing_ratio"],
)

model = TabCSDI(config, "cpu").to("cpu")
current_time = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
foldername = "./save/data_fold" + str(5) + "_" + current_time + "/"

model.load_state_dict(torch.load("./save/data_fold5_20240327_233431" + "/model.pth"))
evaluate_onehot(
    exe_name, model, test_loader, nsample=100, scaler=1, foldername=foldername
)

/home/ksha712/.local/Python-3.10-gimkl-2022a/lib/python3.10/site-packages/torch/nn/modules/transformer.py:286: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}")


--------Normalized dataset loaded--------
Dataset size:2000 entries
--------Normalized dataset loaded--------
--------Normalized dataset loaded--------
--------Normalized dataset loaded--------
Training dataset size: 1600
Validation dataset size: 0
Testing dataset size: 400
[0, 1, 2] {'3': [3, 4]}
[0, 1, 2] {'3': [3, 4]}


  0%|          | 0/25 [02:13<?, ?it/s]


IndexError: index 4 is out of bounds for dimension 0 with size 4